/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package macroprobabilidad;

/**
 *
 * @author dayan
 */
public class adivina extends javax.swing.JPanel {

    /**
     * Creates new form ADIVINA
     */
    public adivina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        procedimiento = new java.awt.TextArea();
        resultado = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        posiblesuma = new java.awt.TextField();
        bopciones = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        procedimiento.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        resultado.setBackground(new java.awt.Color(255, 255, 255));
        resultado.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adivina el valor");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("Cual es la probabilidad de obtener los siguientes valores:");

        posiblesuma.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        posiblesuma.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        posiblesuma.setText("6");
        posiblesuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posiblesumaActionPerformed(evt);
            }
        });
        posiblesuma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                posiblesumaKeyTyped(evt);
            }
        });

        bopciones.setBackground(new java.awt.Color(0, 0, 0));
        bopciones.setEditable(true);
        bopciones.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        bopciones.setForeground(new java.awt.Color(255, 255, 255));
        bopciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Menor", "Menor o igual", "Igual", "Mayor o igual", "Mayor" }));
        bopciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bopcionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(posiblesuma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(bopciones, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(procedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bopciones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posiblesuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(procedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void posiblesumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posiblesumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posiblesumaActionPerformed

    private void posiblesumaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_posiblesumaKeyTyped
       
        char c = evt.getKeyChar();      
        if (c<'0' || c>'9' ) evt.consume();
    }//GEN-LAST:event_posiblesumaKeyTyped

    private void bopcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bopcionesActionPerformed
  int numero=0;
  double operacion,operacion2;  
  String numer,opcio;     
       numer = posiblesuma.getText();    
       opcio = (String)bopciones.getSelectedItem();
       sumatoria3 obj = new sumatoria3();
       obj.validarnumero(numer);
       numero = obj.numerofav(); 
  if(numero==9){
   resultado.setText( "No es posibles obtener ese valor");    
   procedimiento.setText(" Sin procedimiento");
   procedimiento.setEditable(false);
  }   
  else{
  if (opcio.equals("Menor")){
      
   obj.validarnumero(numer);
   obj.menor();
   numero = obj.numerofav();   
   operacion =(double) numero/6;
   operacion2 = (double) operacion*100;   
   resultado.setText( "Probabilidad:  "+String.format("Valor: %.2f", operacion2)+"%"); 
   procedimiento.setEditable(false);
   procedimiento.setText("Procedimiento:");
   procedimiento.append("\nUtilizaremos la regla de LAPLACE ");
   procedimiento.append("\nP(A)= N° casos favorables / N° casos posibles ");
   procedimiento.append("\n");
   procedimiento.append("\nHay 6 casos posibles  ya que ");
   procedimiento.append("\nun dado tiene solo 6 caras");
   procedimiento.append("\n");
   procedimiento.append("\nLos casos favorables se hallaron ");
   procedimiento.append("\nmediante un espacio muestral,  ");
   procedimiento.append("\nanalizando los 6 posibles resultados ");
   procedimiento.append("\n");
   procedimiento.append("\nObteniendo los casos favorables podemos");
  procedimiento.append("\nllegar al resultado:");
  procedimiento.append("\n");
  procedimiento.append("\n  "+numero+" / "+"6 "+" =  "+String.format("Valor: %.3f", operacion2)+" % ");
         }
  if (opcio.equals("Menor o igual")){

   obj.validarnumero(numer);
   obj.menoroigual();
   numero = obj.numerofav();   
   operacion =(double) numero/6;
   operacion2 = (double) operacion*100;   
   resultado.setText( "Probabilidad:  "+String.format("Valor: %.2f", operacion2)+"%");
   procedimiento.setEditable(false);
   procedimiento.setText("Procedimiento:");
   procedimiento.append("\nUtilizaremos la regla de LAPLACE ");
   procedimiento.append("\nP(A)= N° casos favorables / N° casos posibles ");
   procedimiento.append("\n");
   procedimiento.append("\nHay 6 casos posibles  ya que ");
   procedimiento.append("\nun dado tiene solo 6 caras");
   procedimiento.append("\n");
   procedimiento.append("\nLos casos favorables se hallaron ");
   procedimiento.append("\nmediante un espacio muestral,  ");
   procedimiento.append("\nanalizando los 6 posibles resultados ");
   procedimiento.append("\n");
   procedimiento.append("\nObteniendo los casos favorables podemos");
  procedimiento.append("\nllegar al resultado:");
  procedimiento.append("\n");
  procedimiento.append("\n  "+numero+" / "+"6 "+" =  "+String.format("Valor: %.3f", operacion2)+" % ");
         }
  if (opcio.equals("Igual")){

   obj.validarnumero(numer);
   obj.igual();
   numero = obj.numerofav();   
   operacion =(double) numero/6;
   operacion2 = (double) operacion*100;   
   resultado.setText( "Probabilidad:  "+String.format("Valor: %.2f", operacion2)+"%");
   procedimiento.setEditable(false);
   procedimiento.setText("Procedimiento:");
   procedimiento.append("\nUtilizaremos la regla de LAPLACE ");
   procedimiento.append("\nP(A)= N° casos favorables / N° casos posibles ");
   procedimiento.append("\n");
   procedimiento.append("\nHay 6 casos posibles  ya que ");
   procedimiento.append("\nun dado tiene solo 6 caras");
   procedimiento.append("\n");
   procedimiento.append("\nLos casos favorables se hallaron ");
   procedimiento.append("\nmediante un espacio muestral,  ");
   procedimiento.append("\nanalizando los 6 posibles resultados ");
   procedimiento.append("\n");
   procedimiento.append("\nObteniendo los casos favorables podemos");
  procedimiento.append("\nllegar al resultado:");
  procedimiento.append("\n");
  procedimiento.append("\n  "+numero+" / "+"6 "+" =  "+String.format("Valor: %.3f", operacion2)+" % ");
         }
  if (opcio.equals("Mayor o igual")){

   obj.validarnumero(numer);
   obj.mayoroigual();
   numero = obj.numerofav();   
   operacion =(double) numero/6;
   operacion2 = (double) operacion*100;   
   resultado.setText( "Probabilidad:  "+String.format("Valor: %.2f", operacion2)+"%");
   procedimiento.setEditable(false);
   procedimiento.setText("Procedimiento:");
   procedimiento.append("\nUtilizaremos la regla de LAPLACE ");
   procedimiento.append("\nP(A)= N° casos favorables / N° casos posibles ");
   procedimiento.append("\n");
   procedimiento.append("\nHay 6 casos posibles  ya que ");
   procedimiento.append("\nun dado tiene solo 6 caras");
   procedimiento.append("\n");
   procedimiento.append("\nLos casos favorables se hallaron ");
   procedimiento.append("\nmediante un espacio muestral,  ");
   procedimiento.append("\nanalizando los 6 posibles resultados ");
   procedimiento.append("\n");
   procedimiento.append("\nObteniendo los casos favorables podemos");
  procedimiento.append("\nllegar al resultado:");
  procedimiento.append("\n");
  procedimiento.append("\n  "+numero+" / "+"6 "+" =  "+String.format("Valor: %.3f", operacion2)+" % ");
         }
  if (opcio.equals("Mayor")){

   obj.validarnumero(numer);
   obj.mayor();
   numero = obj.numerofav();   
   operacion =(double) numero/6;
   operacion2 = (double) operacion*100;   
   resultado.setText( "Probabilidad:  "+String.format("Valor: %.2f", operacion2)+"%");
   procedimiento.setEditable(false);
   procedimiento.setText("Procedimiento:");
   procedimiento.append("\nUtilizaremos la regla de LAPLACE ");
   procedimiento.append("\nP(A)= N° casos favorables / N° casos posibles ");
   procedimiento.append("\n");
   procedimiento.append("\nHay 6 casos posibles  ya que ");
   procedimiento.append("\nun dado tiene solo 6 caras");
   procedimiento.append("\n");
   procedimiento.append("\nLos casos favorables se hallaron ");
   procedimiento.append("\nmediante un espacio muestral,  ");
   procedimiento.append("\nanalizando los 6 posibles resultados ");
   procedimiento.append("\n");
   procedimiento.append("\nObteniendo los casos favorables podemos");
  procedimiento.append("\nllegar al resultado:");
  procedimiento.append("\n");
  procedimiento.append("\n  "+numero+" / "+"6 "+" =  "+String.format("Valor: %.3f", operacion2)+" % ");
         }
  }
    }//GEN-LAST:event_bopcionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bopciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.TextField posiblesuma;
    private java.awt.TextArea procedimiento;
    private java.awt.Label resultado;
    // End of variables declaration//GEN-END:variables
}
